apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "kubecluster1"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "kubecluster1"
    spec:
      containers:
        - name: "kubecluster1"
          image: "manicontainerregistry.azurecr.io/kubecluster1"
          ports:
          - containerPort: 8080